<a href="https://colab.research.google.com/github/uubs/ipynb_repo/blob/main/pytorch_linear_layer_illustrated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Layer(线性层）

In [3]:
import torch

in_features = torch.tensor([1,2,3,4], dtype=torch.float32)

# 权重矩阵，将一个有4个元素的一维张量映射为一个有三个元素的一维张量
weight_matrix = torch.tensor([
  [1,2,3,4],
  [2,3,4,5],
  [3,4,5,6]
],dtype=torch.float32)

res = weight_matrix.matmul(in_features)
print(res)

tensor([30., 40., 50.])


linear层的工作原理，它使用权重矩阵将一个`in_feature`空间映射到一个`out_feature`空间

In [6]:
# pytorch 中创建一个Linear层，将会随机生成一个4x3的weight_matrix
fc = torch.nn.Linear(in_features=4, out_features=3, bias=False)
fc(in_features)

tensor([ 0.8826,  0.2451, -2.3619], grad_fn=<SqueezeBackward3>)

In [9]:
# 显示的设置fc的weight_matrix为我们之前定义的matrix, bias=False
fc = torch.nn.Linear(in_features=4, out_features=3, bias=False)
fc.weight = torch.nn.Parameter(weight_matrix)
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

In [11]:
# 显示的设置fc的weight_matrix为我们之前定义的matrix, bias=True
fc = torch.nn.Linear(in_features=4, out_features=3, bias=True)
fc.weight = torch.nn.Parameter(weight_matrix)
fc(in_features)

tensor([30.0497, 40.2534, 50.4212], grad_fn=<AddBackward0>)

`Linear Layer`又称为`Full-connected Layer`,是对特征的线性变换。

In [ ]:
torch.nn.Linear(in_features,out_features,bias=True)

- in_features:输入节点数
- out_features:输出节点数
- bias:是否需要偏置
计算公式
$$
y = xW^T + bias
$$

# Activation Function Layer（激活函数层）

nn.Sigmoid